# Pandas - Operações

In [1]:
import pandas as pd

In [4]:
dataframe_1 = pd.read_csv('Pokemon.csv')
dataframe_1.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

### Média

Função mean()

In [5]:
dataframe_1['HP'].mean()

69.25875

In [6]:
dataframe_1.HP.mean()

69.25875

### Mediana

Função median()

In [7]:
dataframe_1.Attack.median()

75.0

### Desvio Padrão

Função std()

In [8]:
dataframe_1['Defense'].std()

31.183500559332934

### Operações entre colunas

In [9]:
dataframe_1.HP + dataframe_1.Attack

0       94
1      122
2      162
3      180
4       91
      ...
795    150
796    210
797    190
798    240
799    190
Length: 800, dtype: int64

In [10]:
dataframe_1.HP - dataframe_1.Attack

0       -4
1       -2
2       -2
3      -20
4      -13
      ...
795    -50
796   -110
797    -30
798    -80
799    -30
Length: 800, dtype: int64

In [11]:
dataframe_1.HP * dataframe_1.Attack

0       2205
1       3720
2       6560
3       8000
4       2028
       ...
795     5000
796     8000
797     8800
798    12800
799     8800
Length: 800, dtype: int64

In [12]:
dataframe_1.HP / dataframe_1.Attack

0      0.918367
1      0.967742
2      0.975610
3      0.800000
4      0.750000
         ...
795    0.500000
796    0.312500
797    0.727273
798    0.500000
799    0.727273
Length: 800, dtype: float64

### Adicionando condições às consultas

#### Operadores Condicionais
#### > maior
#### >= maior ou igual
#### < menor
#### <= menor ou igual
#### == igual
#### != diferente

In [13]:
# Difícil visualização e entendimento, pois imprime a condição para cada linha
dataframe_1['Name'] == 'Venusaur'

0      False
1      False
2       True
3      False
4      False
       ...
795    False
796    False
797    False
798    False
799    False
Name: Name, Length: 800, dtype: bool

In [25]:
dataframe_1[dataframe_1['Name'] == 'Venusaur']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False

In [15]:
dataframe_1[dataframe_1.Name == 'Venusaur']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False

In [22]:
dataframe_1[dataframe_1.HP == 80]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
60,55,Golduck,Water,NaN,500,80,82,78,95,80,85,1,False
73,67,Machoke,Fighting,NaN,405,80,100,70,50,60,45,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
79,73,Tentacruel,Water,Poison,515,80,70,65,80,120,100,1,False
82,76,Golem,Rock,Ground,495,80,120,130,55,65,45,1,False
95,88,Grimer,Poison,NaN,325,80,80,50,40,50,25,1,False
119,111,Rhyhorn,Ground,Rock,345,80,85,95,30,30,25,1,False
128,119,Seaking,Water,NaN,450,80,92,65,65,80,68,1,False
153,142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
295,272,Ludicolo,Water,Grass,480,80,70,70,90,100,70,3,False
312,288,Vigoroth,Normal,NaN,440,80,80,80,55,55,90,3,False
357,326,Grumpig,Psychic,NaN,470,80,45,65,90,110,80,3,False
361,330,Flygon,Ground,Dragon,520,80,100,80,80,80,100,3,False
396,362,Glalie,Ice,NaN,480,80,80,80,80,80,80,3,False
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False
412,376,Metagross,Steel,Psychic,600,80,135,130,95,90,70,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
414,377,Regirock,Rock,NaN,580,80,100,200,50,100,50,3,True
415,378,Regice,Ice,NaN,580,80,50,100,100,200,50,3,True
416,379,Registeel,Steel,NaN,580,80,75,150,75,150,50,3,True
417,380,Latias,Dragon,Psychic,600,80,80,90,110,130,110,3,True
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
419,381,Latios,Dragon,Psychic,600,80,90,80,130,110,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
450,405,Luxray,Electric,NaN,523,80,120,79,95,79,70,4,False
538,481,Mesprit,Psychic,NaN,580,80,105,105,105,105,80,4,True
547,489,Phione,Water,NaN,480,80,80,80,80,80,80,4,False
580,521,Unfezant,Normal,Flying,488,80,115,80,65,55,93,5,False
630,569,Garbodor,Poison,NaN,474,80,95,82,60,82,75,5,False
647,586,Sawsbuck,Normal,Grass,475,80,100,70,60,70,95,5,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
734,666,Vivillon,Bug,Flying,411,80,52,50,90,50,89,6,False
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [23]:
dataframe_1.loc[dataframe_1.HP == 80]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
60,55,Golduck,Water,NaN,500,80,82,78,95,80,85,1,False
73,67,Machoke,Fighting,NaN,405,80,100,70,50,60,45,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
79,73,Tentacruel,Water,Poison,515,80,70,65,80,120,100,1,False
82,76,Golem,Rock,Ground,495,80,120,130,55,65,45,1,False
95,88,Grimer,Poison,NaN,325,80,80,50,40,50,25,1,False
119,111,Rhyhorn,Ground,Rock,345,80,85,95,30,30,25,1,False
128,119,Seaking,Water,NaN,450,80,92,65,65,80,68,1,False
153,142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
295,272,Ludicolo,Water,Grass,480,80,70,70,90,100,70,3,False
312,288,Vigoroth,Normal,NaN,440,80,80,80,55,55,90,3,False
357,326,Grumpig,Psychic,NaN,470,80,45,65,90,110,80,3,False
361,330,Flygon,Ground,Dragon,520,80,100,80,80,80,100,3,False
396,362,Glalie,Ice,NaN,480,80,80,80,80,80,80,3,False
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False
412,376,Metagross,Steel,Psychic,600,80,135,130,95,90,70,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
414,377,Regirock,Rock,NaN,580,80,100,200,50,100,50,3,True
415,378,Regice,Ice,NaN,580,80,50,100,100,200,50,3,True
416,379,Registeel,Steel,NaN,580,80,75,150,75,150,50,3,True
417,380,Latias,Dragon,Psychic,600,80,80,90,110,130,110,3,True
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
419,381,Latios,Dragon,Psychic,600,80,90,80,130,110,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
450,405,Luxray,Electric,NaN,523,80,120,79,95,79,70,4,False
538,481,Mesprit,Psychic,NaN,580,80,105,105,105,105,80,4,True
547,489,Phione,Water,NaN,480,80,80,80,80,80,80,4,False
580,521,Unfezant,Normal,Flying,488,80,115,80,65,55,93,5,False
630,569,Garbodor,Poison,NaN,474,80,95,82,60,82,75,5,False
647,586,Sawsbuck,Normal,Grass,475,80,100,70,60,70,95,5,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
734,666,Vivillon,Bug,Flying,411,80,52,50,90,50,89,6,False
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [26]:
# Imprime os nomes dos Pokemons que satisfazem a condição de HP == 80
dataframe_1.loc[dataframe_1.HP == 80, ['Name']]

                          Name
2                     Venusaur
3        VenusaurMega Venusaur
60                     Golduck
73                     Machoke
77                  Victreebel
79                  Tentacruel
82                       Golem
95                      Grimer
119                    Rhyhorn
128                    Seaking
153                 Aerodactyl
154  AerodactylMega Aerodactyl
168                   Meganium
231                  Heracross
232    HeracrossMega Heracross
278                   Blaziken
279      BlazikenMega Blaziken
295                   Ludicolo
312                   Vigoroth
357                    Grumpig
361                     Flygon
396                     Glalie
397          GlalieMega Glalie
412                  Metagross
413    MetagrossMega Metagross
414                   Regirock
415                     Regice
416                  Registeel
417                     Latias
418          LatiasMega Latias
419                     Latios
420          LatiosMega Latios
450                     Luxray
538                    Mesprit
547                     Phione
580                   Unfezant
630                   Garbodor
647                   Sawsbuck
678                   Accelgor
734                   Vivillon
797        HoopaHoopa Confined
798         HoopaHoopa Unbound
799                  Volcanion

In [27]:
dataframe_1.loc[dataframe_1.HP == 80, ['Name','Type 1']]

                          Name    Type 1
2                     Venusaur     Grass
3        VenusaurMega Venusaur     Grass
60                     Golduck     Water
73                     Machoke  Fighting
77                  Victreebel     Grass
79                  Tentacruel     Water
82                       Golem      Rock
95                      Grimer    Poison
119                    Rhyhorn    Ground
128                    Seaking     Water
153                 Aerodactyl      Rock
154  AerodactylMega Aerodactyl      Rock
168                   Meganium     Grass
231                  Heracross       Bug
232    HeracrossMega Heracross       Bug
278                   Blaziken      Fire
279      BlazikenMega Blaziken      Fire
295                   Ludicolo     Water
312                   Vigoroth    Normal
357                    Grumpig   Psychic
361                     Flygon    Ground
396                     Glalie       Ice
397          GlalieMega Glalie       Ice
412                  Metagross     Steel
413    MetagrossMega Metagross     Steel
414                   Regirock      Rock
415                     Regice       Ice
416                  Registeel     Steel
417                     Latias    Dragon
418          LatiasMega Latias    Dragon
419                     Latios    Dragon
420          LatiosMega Latios    Dragon
450                     Luxray  Electric
538                    Mesprit   Psychic
547                     Phione     Water
580                   Unfezant    Normal
630                   Garbodor    Poison
647                   Sawsbuck    Normal
678                   Accelgor       Bug
734                   Vivillon       Bug
797        HoopaHoopa Confined   Psychic
798         HoopaHoopa Unbound   Psychic
799                  Volcanion      Fire

In [28]:
# Todos os pokemons que o valor de HP é maior do que o seu Attack
dataframe_1.loc[dataframe_1.HP > dataframe_1.Attack]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,700,Sylveon,Fairy,NaN,525,95,65,65,110,130,60,6,False
772,702,Dedenne,Electric,Fairy,431,67,58,57,81,67,101,6,False
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [31]:
# Todos os pokemons que possuem HP maior que a média de HP de todos
dataframe_1.loc[dataframe_1.HP > dataframe_1.HP.mean()]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

#### Operadores Lógicos
#### & e
#### | ou
#### ~ negação

In [34]:
# Imprimir todos que possuem HP menor que 50 ou maior que 90
dataframe_1.loc[(dataframe_1.HP<50) | (dataframe_1.HP>90)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
789,713,Avalugg,Ice,NaN,514,95,117,184,44,46,28,6,False
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [35]:
# Imprimir todos os que possuem o Defense entre 50 e 80
dataframe_1[(dataframe_1.Defense>50) & (dataframe_1.Defense<80)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,710,PumpkabooSmall Size,Ghost,Grass,335,44,66,70,44,55,56,6,False
782,710,PumpkabooLarge Size,Ghost,Grass,335,54,66,70,44,55,46,6,False
783,710,PumpkabooSuper Size,Ghost,Grass,335,59,66,70,44,55,41,6,False
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

In [36]:
# Imprimir todos os que possuem HP maior que 60 e Defense menor que 40
dataframe_1[(dataframe_1.HP>60) & (dataframe_1.Defense<40)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
44,39,Jigglypuff,Normal,Fairy,270,115,45,20,45,25,20,1,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
133,124,Jynx,Ice,Psychic,455,65,50,35,115,95,95,1,False
184,170,Chinchou,Water,Electric,330,75,38,38,56,56,67,2,False
188,174,Igglybuff,Normal,Fairy,210,90,30,15,40,20,15,2,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
317,293,Whismur,Normal,NaN,240,64,51,23,51,23,28,3,False
320,296,Makuhita,Fighting,NaN,237,72,60,30,20,30,25,3,False
350,320,Wailmer,Water,NaN,400,130,70,35,70,35,60,3,False
472,425,Drifloon,Ghost,Flying,348,90,50,34,60,44,70,4,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
676,615,Cryogonal,Ice,NaN,485,70,50,30,95,135,105,5,False

#### Condição e definindo quais colunas deve exibir

In [38]:
dataframe_1.loc[(dataframe_1.HP>60) & (dataframe_1.Defense<40), ['Name', 'Type 1']]

           Name    Type 1
44   Jigglypuff    Normal
121     Chansey    Normal
133        Jynx       Ice
184    Chinchou     Water
188   Igglybuff    Normal
261     Blissey    Normal
317     Whismur    Normal
320    Makuhita  Fighting
350     Wailmer     Water
472    Drifloon     Ghost
488     Happiny    Normal
676   Cryogonal       Ice

#### Adicionando coluna no dataframe com um valor padrão

In [39]:
dataframe_1['Numero'] = 1
dataframe_1

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Numero
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,1
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,1
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,1
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,1
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,1

In [41]:
dataframe_1.loc[:,'Disponibilidade'] = True
dataframe_1

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Numero,Disponibilidade
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1,True
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,1,True
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,1,True
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,1,True
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,1,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,1,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,1,True

In [42]:
dataframe_1.insert(loc=1,column='Preco',value=0)
dataframe_1

,#,Preco,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Numero,Disponibilidade
0,1,0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1,True
1,2,0,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,1,True
2,3,0,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,1,True
3,3,0,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,1,True
4,4,0,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,0,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,1,True
796,719,0,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1,True
797,720,0,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1,True
798,720,0,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,1,True
799,721,0,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,1,True

#### Adicionando coluna no dataframe a partir de um cálculo usando outra coluna

In [3]:
#### Inserindo linhas ao dataframe a partir de outro

In [4]:
dicionario_1 = {
    '#': [722, 723],
    'Name': ['Nome1','Nome2'],
    'Type 1':['Rock','Psychic'],
    'Type 2':['Poison','Ghost'],
    'Total':[500,300],
    'HP':[60,45],
    'Attack':[66, 42],
    'Defense':[100, 90],
    'Sp. Atk':[150, 144],
    'Sp. Def':[123, 130],
    'Speed':[60, 30],
    'Generation':[1, 2],
    'Legendary':[False, True],
    'Number':[1, 1],
    'Available':[False, False],
    'Price':[33, 21],
}
dataframe_3 = pd.DataFrame(dicionario_1)
dataframe_3

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Number,Available,Price
0,722,Nome1,Rock,Poison,500,60,66,100,150,123,60,1,False,1,False,33
1,723,Nome2,Psychic,Ghost,300,45,42,90,144,130,30,2,True,1,False,21

#### Excluindo linhas inteiras

#### Excluindo linhas que atendem a alguma condição

#### Excluindo colunas